'use client';
import { useEffect, useState } from 'react';

const API = '/api';
const schemas: Record<string, { title: string; fields: string[] }> = {
  courses: { title: 'Cursos', fields: ['name','slug','description','image','duration','modality','area','status','featured','objectives','careerProfile','requirements','curriculum','schedule','location','metaTitle','metaDescription'] },
  events: { title: 'Eventos', fields: ['title','slug','description','image','video','startsAt','endsAt','publishAt','time','location','speaker','registrationUrl','status','publication','metaTitle','metaDescription'] },
  campaigns: { title: 'Publicidade', fields: ['title','subtitle','description','image','video','buttonText','url','startsAt','endsAt','order','pages','status'] },
  news: { title: 'Notícias', fields: ['title','slug','summary','content','image','video','author','category','tags','status','publishAt','metaTitle','metaDescription'] },
  leads: { title: 'Interessados', fields: ['name','phone','whatsapp','email','course','municipality','notes','status'] },
  users: { title: 'Utilizadores', fields: ['name','email','password','role','active'] },
  media: { title: 'Biblioteca de mídia', fields: ['originalName','filename','url','mimeType','category'] },
  audit: { title: 'Auditoria', fields: ['action','entity','entityId','details','createdAt'] },
};
const navigation = [['overview','▦','Visão geral'],['courses','▤','Cursos'],['events','◷','Eventos'],['campaigns','▧','Publicidade'],['news','▤','Notícias'],['media','▣','Biblioteca de mídia'],['leads','◉','Interessados'],['users','♙','Utilizadores'],['home','⌂','Página inicial'],['settings','⚙','Configurações'],['audit','≡','Auditoria']];
const label = (s: string) => s.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());

export default function Admin() {
  const [token,setToken]=useState(''),[user,setUser]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
  const [tab,setTab]=useState('overview'),[rows,setRows]=useState<any[]>([]),[stats,setStats]=useState<any>({}),[settings,setSettings]=useState<any>({}),[homeSections,setHomeSections]=useState<any[]>([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{const t=localStorage.getItem('ps_token');if(t){setToken(t);fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.ok?r.json():null).then(u=>{if(u)setUser(u);else localStorage.removeItem('ps_token')}).catch(()=>{})}},[]);
  useEffect(()=>{if(user&&token)void load(tab)},[user,token,tab]);
  async function request(path:string,init:any={}){const res=await fetch(`${API}${path}`,{...init,headers:{...(init.body instanceof FormData?{}:{'Content-Type':'application/json'}),Authorization:`Bearer ${token}`,...init.headers}});if(!res.ok){const body=await res.json().catch(()=>({}));throw new Error(body.message||'Não foi possível concluir a operação.')}return res}
  async function login(e:any){e.preventDefault();setError('');try{const res=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Credenciais inválidas');localStorage.setItem('ps_token',data.token);setToken(data.token);setUser(data.user)}catch(e:any){setError(e.message)}}
  async function load(section:string){setLoading(true);try{if(section==='overview')setStats(await(await request('/admin/dashboard')).json());else if(section==='settings')setSettings(await(await request('/admin/settings')).json());else if(section==='home')setHomeSections(await(await request('/admin/sections')).json());else setRows(await(await request(`/admin/${section}`)).json())}catch(e:any){flash(e.message)}finally{setLoading(false)}}
  function flash(s:string){setNotice(s);setTimeout(()=>setNotice(''),3500)}
  async function create(e:any){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{await request(`/admin/${tab}`,{method:'POST',body:JSON.stringify(data)});form.reset();flash('Registo criado.');void load(tab)}catch(e:any){flash(e.message)}}
  async function update(id:string,data:any){try{await request(`/admin/${tab}/${id}`,{method:'PUT',body:JSON.stringify(data)});flash('Alterações guardadas.');void load(tab)}catch(e:any){flash(e.message)}}
  async function remove(id:string){if(!confirm('Remover este registo?'))return;try{await request(`/admin/${tab}/${id}`,{method:'DELETE'});flash('Registo removido.');void load(tab)}catch(e:any){flash(e.message)}}
  async function saveSettings(e:any){e.preventDefault();try{await request('/admin/settings',{method:'PUT',body:JSON.stringify(settings)});flash('Configurações guardadas.')}catch(e:any){flash(e.message)}}
  async function saveSection(s:any){try{await request(`/admin/home-sections/${s.id}`,{method:'PUT',body:JSON.stringify(s)});flash('Secção actualizada.')}catch(e:any){flash(e.message)}}
  async function upload(e:any){const files=Array.from(e.target.files||[]) as File[];e.target.value='';if(!files.length)return;let sent=0;try{for(const file of files){const form=new FormData();form.append('file',file);await request('/admin/upload',{method:'POST',body:form});sent++}flash(`${sent} ficheiro(s) carregado(s).`);void load('media')}catch(e:any){flash(`${sent} ficheiro(s) carregado(s). ${e.message}`);void load('media')}}
  async function exportXlsx(){try{const res=await request('/admin/leads/export.xlsx');const href=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=href;a.download='interessados.xlsx';a.click();URL.revokeObjectURL(href)}catch(e:any){flash(e.message)}}
  async function exportCsv(){try{const res=await request('/admin/leads/export.csv');const href=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=href;a.download='interessados.csv';a.click();URL.revokeObjectURL(href)}catch(e:any){flash(e.message)}}
  if(!user)return <main className="login"><a href="/" className="brand"><img src="/logo_paraiso_do_saber.jpeg"/><span><b>PARAÍSO DO SABER</b><small>ÁREA ADMINISTRATIVA</small></span></a><form onSubmit={login}><label>PAINEL DE GESTÃO</label><h1>Bem-vindo de volta.</h1><p>Aceda com a sua conta administrativa.</p><input type="email" required placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Palavra-passe" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<small className="error">{error}</small>}<button className="btn">Entrar no painel ↗</button><a href="/recuperar-senha">Esqueci-me da palavra-passe</a><small>Conta inicial configurada no servidor.</small></form></main>;
  const schema=schemas[tab];
  return <div className="admin-shell"><aside className="admin-side"><a href="/" className="brand"><img src="/logo_paraiso_do_saber.jpeg"/><span><b>PARAÍSO DO SABER</b><small>PAINEL ADMINISTRATIVO</small></span></a><small className="side-label">GESTÃO DO PORTAL</small>{navigation.filter(([key])=>user.role==='ADMIN'||(user.role==='EDITOR'&&['overview','courses','events','campaigns','news','media','home'].includes(key))||(user.role==='ATTENDANCE'&&['overview','leads'].includes(key))).map(([key,icon,text])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><span>{icon}</span>{text}</button>)}<div className="admin-user"><b>{user.name}</b><small>{user.role}</small><button onClick={()=>{void request('/auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('ps_token');setUser(null);setToken('')}}>Terminar sessão</button></div></aside>
  <main className="admin-content"><header className="admin-head"><div><small>PORTAL DO INSTITUTO</small><h1>{tab==='overview'?'Visão geral':tab==='home'?'Página inicial':schema?.title||label(tab)}</h1></div><a href="/">Ver site ↗</a></header>{notice&&<div className="notice">{notice}</div>}
  {tab==='overview'&&<><div className="stats">{[['Cursos activos',stats.courses],['Próximos eventos',stats.events],['Campanhas activas',stats.campaigns],['Notícias publicadas',stats.news],['Interessados',stats.leads],['Ficheiros',stats.media]].map(([name,value])=><article key={name}><small>{name}</small><b>{value??'—'}</b></article>)}</div><section className="admin-box"><h2>Gestão do portal</h2><p>Actualize cursos, publique notícias, organize campanhas e acompanhe os pedidos de informação num só lugar.</p></section></>}
  {tab==='settings'&&<form className="admin-box settings-form" onSubmit={saveSettings}><h2>Informações gerais do Instituto</h2>{Object.entries({institutionName:'Nome do Instituto',logo:'Logotipo (caminho ou URL)',favicon:'Favicon',phone1:'Telefone principal',phone2:'Telefone alternativo',whatsapp:'WhatsApp (somente números)',email:'E-mail',address:'Endereço',facebook:'Facebook',instagram:'Instagram',tiktok:'TikTok',youtube:'YouTube',officeHours:'Horário de atendimento',footer:'Texto do rodapé',metaTitle:'Título SEO',metaDescription:'Descrição SEO'}).map(([key,text])=><label key={key}>{text}<input value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<StaticSeoSettings settings={settings} onChange={(key,value)=>setSettings({...settings,[key]:value})}/><button className="btn">Guardar configurações</button></form>}
  {tab==='home'&&<div className="section-admin">{homeSections.map(s=><article className="admin-box section-edit" key={s.id}><label className="check"><input type="checkbox" checked={s.enabled} onChange={e=>setHomeSections(homeSections.map(x=>x.id===s.id?{...x,enabled:e.target.checked}:x))}/> Secção activa</label><input value={s.title||''} placeholder="Título" onChange={e=>setHomeSections(homeSections.map(x=>x.id===s.id?{...x,title:e.target.value}:x))}/><textarea value={s.description||''} placeholder="Descrição" onChange={e=>setHomeSections(homeSections.map(x=>x.id===s.id?{...x,description:e.target.value}:x))}/><label>Ordem<input type="number" value={s.order} onChange={e=>setHomeSections(homeSections.map(x=>x.id===s.id?{...x,order:+e.target.value}:x))}/></label><button className="btn" onClick={()=>saveSection(s)}>Guardar secção</button></article>)}</div>}
  {tab==='media'&&<section className="admin-box"><h2>Biblioteca de mídia</h2><p>Imagens, vídeos e documentos (máximo 100 MB por ficheiro).</p><label className="media-upload">Adicionar ficheiros<input type="file" multiple accept="image/*,video/*,application/pdf" onChange={upload}/></label></section>}
  {schema&&<><section className="admin-box"><div className="box-head"><div><h2>{schema.title}</h2><p>{tab==='leads'?'Acompanhe pedidos de informação e matrícula.':'Crie e actualize o conteúdo do portal.'}</p></div>{tab==='leads'&&<div className="export-actions"><button className="btn" onClick={exportXlsx}>Exportar Excel (.xlsx) ↓</button><button className="remove" onClick={exportCsv}>CSV</button></div>}</div>{tab!=='audit'&&tab!=='media'&&<form className="record-form" onSubmit={create}>{schema.fields.map(k=><label key={k}>{label(k)}{['description','summary','content','notes','objectives','careerProfile','requirements','curriculum','metaDescription'].includes(k)?<textarea name={k} placeholder={label(k)}/>:['publication','role','status'].includes(k)?<select name={k}><option value="">Padrão</option>{(k==='role'?['ADMIN','EDITOR','ATTENDANCE']:k==='publication'?['DRAFT','PUBLISHED','SCHEDULED','ARCHIVED']:tab==='leads'?['NEW','CONTACTED','NEGOTIATING','ENROLLED','NOT_INTERESTED']:tab==='courses'?['ACTIVE','INACTIVE','CLOSED']:['news','campaigns'].includes(tab)?['DRAFT','PUBLISHED','SCHEDULED','ARCHIVED']:['UPCOMING','ONGOING','ENDED']).map(v=><option key={v}>{v}</option>)}</select>:['featured','active'].includes(k)?<select name={k}><option value="false">Não</option><option value="true">Sim</option></select>:<input name={k} type={k==='password'?'password':['startsAt','endsAt','publishAt'].includes(k)?'datetime-local':k==='order'?'number':'text'} placeholder={label(k)}/>}</label>)}<button className="btn">Adicionar registo ↗</button></form>}</section>{tab==='media'?<MediaLibrary rows={rows} onUpdate={update} onRemove={remove}/>:<Records rows={rows} fields={schema.fields} onUpdate={update} onRemove={remove} tab={tab}/>}</>}
  {loading&&<div className="busy">A carregar…</div>}</main></div>;
}

function Records({rows,fields,onUpdate,onRemove,tab}:{rows:any[],fields:string[],onUpdate:(id:string,data:any)=>void,onRemove:(id:string)=>void,tab:string}){
  const [editing,setEditing]=useState<any>(null);
  const [scheduleFilter,setScheduleFilter]=useState('all');
  const scheduledField=tab==='events'?'publication':'status';
  const filteredRows=rows.filter(row=>{if(scheduleFilter==='all')return true;const state=row[scheduledField];const date=Date.parse(row.publishAt||(tab==='campaigns'?row.startsAt:'')||'');if(scheduleFilter==='scheduled')return (state==='SCHEDULED'&&(!date||date>Date.now()))||(date>Date.now()&&state!=='DRAFT');if(scheduleFilter==='draft')return state==='DRAFT';if(scheduleFilter==='published')return (state==='PUBLISHED'||(state==='SCHEDULED'&&date>0&&date<=Date.now()))&&(!date||date<=Date.now())&&!(row.endsAt&&Date.parse(row.endsAt)<Date.now());if(scheduleFilter==='past')return !!row.endsAt&&Date.parse(row.endsAt)<Date.now();return true});
  return <section className="admin-box records">{editing&&<form className="edit-record" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));onUpdate(editing.id,data);setEditing(null)}}><h3>Editar registo</h3><div>{fields.filter(k=>!['createdAt','updatedAt','passwordHash','id'].includes(k)&&(k!=='password'||tab==='users')).map(k=><label key={k}>{label(k)}{['description','summary','content','notes','objectives','careerProfile','requirements','curriculum','details'].includes(k)?<textarea name={k} defaultValue={editing[k]||''}/>:['featured','active','enabled'].includes(k)?<select name={k} defaultValue={String(editing[k]??false)}><option value="true">Sim</option><option value="false">Não</option></select>:<input name={k} type={k==='password'?'password':['startsAt','endsAt','publishAt'].includes(k)?'datetime-local':'text'} placeholder={k==='password'?'Nova palavra-passe (opcional)':undefined} defaultValue={k==='password'?'':typeof editing[k]==='string'&&['startsAt','endsAt','publishAt'].includes(k)?editing[k].replace(' ','T').slice(0,16):editing[k]??''}/>}</label>)}</div><button className="btn">Guardar alterações</button><button type="button" className="remove" onClick={()=>setEditing(null)}>Cancelar</button></form>}
  {['events','campaigns','news'].includes(tab)&&<label className="schedule-filter">Ver registos<select value={scheduleFilter} onChange={e=>setScheduleFilter(e.target.value)}><option value="all">Todos</option><option value="scheduled">Agendados / futuros</option><option value="published">Publicados / activos</option><option value="draft">Rascunhos</option><option value="past">Terminados</option></select><small>Datas no fuso horário configurado para o Instituto.</small></label>}<div className="table-wrap"><table><thead><tr>{fields.slice(0,5).map(k=><th key={k}>{label(k)}</th>)}{tab!=='audit'&&<th>Acções</th>}</tr></thead><tbody>{filteredRows.map((row,i)=><tr key={row.id||i}>{fields.slice(0,5).map(k=><td key={k}>{k==='image'&&row[k]?<img className="thumb" src={row[k].startsWith('/media/')?`${API.replace('/api','')}${row[k]}`:row[k].startsWith('/')?row[k]:`/${row[k]}`}/>:String(row[k]??'—').slice(0,120)}</td>)}{tab!=='audit'&&<td><button className="remove" onClick={()=>setEditing(row)}>Editar</button> &nbsp; <button className="remove" onClick={()=>onRemove(row.id)}>Remover</button></td>}</tr>)}</tbody></table>{filteredRows.length===0&&<p className="empty">Ainda não há registos nesta área.</p>}</div></section>;
}

function StaticSeoSettings({settings,onChange}:{settings:any,onChange:(key:string,value:string)=>void}){
  const pages=[['cursos','Cursos'],['eventos','Eventos'],['noticias','Notícias'],['galeria','Galeria'],['instituto','O Instituto'],['matriculas','Matrículas'],['contactos','Contactos']];
  return <section className="seo-settings"><h3>SEO por página</h3><p>Personalize o título e a descrição que aparecem nos resultados de pesquisa.</p>{pages.map(([key,name])=><div key={key}><b>{name}</b><label>Título (máximo 70 caracteres)<input maxLength={70} value={settings[`metaTitle_${key}`]||''} onChange={e=>onChange(`metaTitle_${key}`,e.target.value)}/></label><label>Descrição (máximo 170 caracteres)<textarea maxLength={170} value={settings[`metaDescription_${key}`]||''} onChange={e=>onChange(`metaDescription_${key}`,e.target.value)}/></label></div>)}</section>;
}

function MediaLibrary({rows,onUpdate,onRemove}:{rows:any[],onUpdate:(id:string,data:any)=>void,onRemove:(id:string)=>void}){
  const [query,setQuery]=useState('');
  const [kind,setKind]=useState('all');
  const filtered=rows.filter(row=>{
    const matches=`${row.originalName} ${row.category||''} ${row.mimeType}`.toLowerCase().includes(query.toLowerCase());
    return matches&&(kind==='all'||(kind==='image'?row.mimeType?.startsWith('image/'):kind==='video'?row.mimeType?.startsWith('video/'):row.mimeType==='application/pdf'));
  });
  return <section className="admin-box media-library"><div className="media-tools"><input aria-label="Pesquisar ficheiros" placeholder="Pesquisar ficheiros ou categoria" value={query} onChange={e=>setQuery(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Todos os tipos</option><option value="image">Imagens</option><option value="video">Vídeos</option><option value="document">PDF</option></select><span>{filtered.length} de {rows.length} ficheiro(s)</span></div><div className="media-grid">{filtered.map(item=><article className="media-card" key={item.id}><a href={item.url?.startsWith('http')?item.url:item.url?.startsWith('/')?item.url:`/${item.url}`} target="_blank" rel="noreferrer" className="media-preview">{item.mimeType?.startsWith('image/')?<img src={item.url} alt={item.originalName}/>:item.mimeType?.startsWith('video/')?<video src={item.url} muted preload="metadata"/>:<span>PDF</span>}</a><div className="media-card-meta"><b title={item.originalName}>{item.originalName}</b><small>{item.mimeType} · {Math.max(1,Math.round(item.size/1024))} KB</small><input aria-label="Nome do ficheiro" defaultValue={item.originalName||''} onBlur={e=>{if(e.target.value!==item.originalName)onUpdate(item.id,{originalName:e.target.value})}}/><input aria-label="Categoria do ficheiro" defaultValue={item.category||'Geral'} onBlur={e=>{if(e.target.value!==item.category)onUpdate(item.id,{category:e.target.value})}}/><div><a href={item.url?.startsWith('http')?item.url:item.url?.startsWith('/')?item.url:`/${item.url}`} target="_blank" rel="noreferrer">Abrir</a><button type="button" onClick={()=>{if(navigator.clipboard)void navigator.clipboard.writeText(new URL(item.url,window.location.origin).toString())}}>Copiar URL</button><button className="remove" onClick={()=>onRemove(item.id)}>Remover</button></div></div></article>)}</div>{filtered.length===0&&<p className="empty">Nenhum ficheiro corresponde à pesquisa.</p>}</section>;
}
