import {useEffect,useState,useRef,type ReactNode} from 'react';
import PublicLayout from './PublicLayout';
import Link from './Link';
import {asset,paths,dateLabel,useTitle,usePortal} from './portal';
import {AdmissionsSteps,FAQ} from './Institutional';

type Kind='courses'|'events'|'news'|'media';
export function PageBanner({eyebrow,title,description,image='/banner2.jpeg',children}:{eyebrow:string,title:string,description:string,image?:string,children?:ReactNode}){
 return <><nav className="in-breadcrumb" aria-label="Localização"><Link href="/">Início</Link><span aria-hidden="true">/</span><span aria-current="page">{title}</span></nav><section className="in-banner"><img src={asset(image)} alt=""/><div className="in-banner-overlay"/><div className="in-banner-content"><span className="ps-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p>{children}</div><div className="in-banner-mark" aria-hidden="true">+</div><span className="in-banner-sign">PARAÍSO DO SABER · EDUCAÇÃO PARA A VIDA</span></section></>
}
export function CallToAction(){return <section className="in-cta"><div><span className="ps-eyebrow">ESTAMOS AQUI PARA AJUDAR</span><h2>Vamos conversar sobre o seu futuro?</h2><p>Conheça os cursos e esclareça as suas dúvidas com a nossa equipa.</p></div><Link className="ps-button ps-yellow" href="/matriculas">Quero saber mais <span>↗</span></Link></section>}
export function EmptyState({error=false,search=false,retry}:{error?:boolean,search?:boolean,retry?:()=>void}){return <div className="in-empty"><span className="in-empty-icon" aria-hidden="true">{error?'!':search?'⌕':'▤'}</span><h2>{error?'Não foi possível carregar o conteúdo':search?'Não encontrámos resultados':'Novidades a caminho'}</h2><p>{error?'Verifique a ligação e tente novamente.':search?'Experimente outro termo ou remova os filtros para ver mais conteúdos.':'Os conteúdos publicados pelo Instituto aparecerão aqui. Entretanto, conheça os nossos cursos ou fale com a secretaria.'}</p>{retry&&<button className="ps-button ps-blue" onClick={retry}>{error?'Tentar novamente':'Limpar filtros'} <span>↗</span></button>}{!error&&!search&&<Link href="/cursos" className="ps-button ps-blue">Conheça os cursos <span>↗</span></Link>}</div>}
const info={courses:{title:'Formação que transforma.',label:'Nossos cursos',intro:'Encontre o seu caminho na área da saúde. Conheça as formações do Paraíso do Saber e dê o próximo passo.',image:'/banner1.jpeg'},events:{title:'Encontros que aproximam.',label:'Agenda do Instituto',intro:'Acompanhe os encontros, actividades e iniciativas que fazem parte da vida do Instituto.',image:'/banner3.jpeg'},news:{title:'O Instituto em notícia.',label:'Notícias e comunicados',intro:'Informação, conhecimento e novidades para a nossa comunidade educativa.',image:'/banner2.jpeg'},media:{title:'Conheça. Veja. Inspire-se.',label:'Galeria multimédia',intro:'Explore os materiais de apresentação do Paraíso do Saber, as nossas imagens e os vídeos institucionais.',image:'/banner3.jpeg'}};
const materials=[{id:'institution-1',originalName:'Formação na área da saúde',url:'/banner1.jpeg',category:'Apresentação institucional',mimeType:'image/jpeg'},{id:'institution-2',originalName:'Conhecimento ao serviço do cuidado',url:'/banner2.jpeg',category:'Apresentação institucional',mimeType:'image/jpeg'},{id:'institution-3',originalName:'Aprender para transformar vidas',url:'/banner3.jpeg',category:'Apresentação institucional',mimeType:'image/jpeg'}];
export function Listing({type}:{type:Kind}){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[q,setQ]=useState(new URLSearchParams(location.search).get('q')||''),[filter,setFilter]=useState('Todos'),[retry,setRetry]=useState(0),[limit,setLimit]=useState(9),[selected,setSelected]=useState<any>(null);
 const dialog=useRef<HTMLDialogElement>(null);const meta=info[type];useTitle(meta.label);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(false);fetch('/api/public/'+type,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setRows).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[type,retry]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close()},[selected]);
 const all=type==='media'?[...rows,...materials]:rows;
 const categories=type==='media'?['Todos','Imagens','Vídeos']:['Todos',...new Set(all.map((r:any)=>r.area||r.category).filter(Boolean))];
 const filtered=all.filter((r:any)=>`${r.name||r.title||r.originalName} ${r.description||r.summary||''}`.toLocaleLowerCase().includes(q.toLocaleLowerCase())&&(filter==='Todos'||(type==='media'?filter==='Imagens':(r.area||r.category)===filter)));
 const videos=Array.from({length:5},(_,i)=>({url:`/publicidade${i+1}.mp4`,name:`Apresentação do Instituto ${String(i+1).padStart(2,'0')}`})).filter(v=>v.name.toLowerCase().includes(q.toLowerCase()));
 const clear=()=>{setQ('');setFilter('Todos')};
 return <PublicLayout><PageBanner eyebrow={meta.label} title={meta.title} description={meta.intro} image={meta.image}><Link href="/matriculas" className="ps-button ps-yellow">{type==='courses'?'Encontre a sua formação':'Faça parte desta comunidade'} <span>↗</span></Link></PageBanner>
  <div className="in-section-intro"><div><span className="ps-eyebrow">PARAÍSO DO SABER</span><h2>{meta.label}</h2></div><p>{type==='courses'?'Cada escolha é o início de uma nova possibilidade. Explore as informações de cada curso.':type==='media'?'Imagens e vídeos de apresentação institucional.':'Consulte as últimas publicações e acompanhe o Instituto.'}</p></div>
  <div className="in-toolbar"><label className="in-search"><span aria-hidden="true">⌕</span><input aria-label={`Pesquisar ${meta.label.toLowerCase()}`} placeholder={type==='courses'?'Que curso procura?':'Pesquisar nesta página…'} value={q} onChange={e=>{setQ(e.target.value);setLimit(9)}}/>{q&&<button aria-label="Limpar pesquisa" onClick={()=>setQ('')}>×</button>}</label><div className="in-filters" aria-label="Filtrar conteúdos">{categories.map(c=><button key={c} aria-pressed={filter===c} onClick={()=>{setFilter(c);setLimit(9)}}>{c}</button>)}</div></div>
  {loading?<div className="in-skeleton-grid" role="status" aria-label="A carregar conteúdos">{[1,2,3].map(i=><div key={i}/>)}</div>:error?<EmptyState error retry={()=>setRetry(n=>n+1)}/>:<>
   {!(type==='media'&&filter==='Vídeos')&&<><div className="in-result-count">{filtered.length} {filtered.length===1?'resultado':'resultados'}{q&&` para “${q}”`}</div><div className={`in-catalogue ${type==='media'?'in-gallery':''}`}>
    {filtered.slice(0,limit).map((r:any)=>type==='media'?<button key={r.id} className="in-gallery-card" onClick={()=>setSelected(r)}><img src={asset(r.url)} alt={r.originalName} loading="lazy"/><div><small>{r.category||'Galeria do Instituto'}</small><h3>{r.originalName}</h3><span aria-hidden="true">↗</span></div></button>:<article key={r.id} className="in-catalogue-card"><Link href={`/${paths[type]}/${r.slug}`} className="in-catalogue-image"><img src={asset(r.image||meta.image)} alt={r.name||r.title} loading="lazy"/><span>{r.area||r.category||(type==='events'?'AGENDA':'FORMAÇÃO EM SAÚDE')}</span></Link><div className="in-card-body">{type==='events'&&<time>{dateLabel(r.startsAt)}</time>}{type==='news'&&r.publishAt&&<time>{dateLabel(r.publishAt)}</time>}<h3><Link href={`/${paths[type]}/${r.slug}`}>{r.name||r.title}</Link></h3><p>{r.description||r.summary}</p>{type==='courses'&&<div className="in-card-meta"><span>✚ Área da saúde</span><span>{r.modality||'Consulte as condições'}</span></div>}<Link className="in-card-link" href={`/${paths[type]}/${r.slug}`}>{type==='courses'?'Conheça esta formação':type==='events'?'Ver detalhes do evento':'Ler publicação'} <span>↗</span></Link></div></article>)}
   </div>{!filtered.length&&<EmptyState search={Boolean(q)||filter!=='Todos'} retry={q||filter!=='Todos'?clear:undefined}/>} {filtered.length>limit&&<button className="ps-button ps-blue in-load-more" onClick={()=>setLimit(n=>n+9)}>Mostrar mais conteúdos ↓</button>}</>}
   {type==='media'&&filter!=='Imagens'&&<section className="in-videos"><div className="ps-section-heading"><div><span className="ps-eyebrow">O INSTITUTO EM MOVIMENTO</span><h2>Vídeos institucionais</h2></div></div><div className="in-video-grid">{videos.map((v,i)=><article key={v.url}><video controls preload="none" poster={`/banner${i%3+1}.jpeg`}><source src={v.url} type="video/mp4"/></video><h3>{v.name}</h3><p>Conheça a apresentação do Paraíso do Saber.</p></article>)}</div>{!videos.length&&filter==='Vídeos'&&<EmptyState search retry={clear}/>}</section>}
  </>}
  {type==='courses'&&<><AdmissionsSteps/><FAQ/></>}<CallToAction/>
  <dialog ref={dialog} className="in-lightbox" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}><button className="in-lightbox-close" aria-label="Fechar imagem" onClick={()=>setSelected(null)}>✕</button>{selected&&<><img src={asset(selected.url)} alt={selected.originalName}/><p>{selected.originalName}</p></>}</dialog>
 </PublicLayout>
}
export function Detail({type,slug}:{type:'courses'|'events'|'news',slug:string}){
 const [item,setItem]=useState<any>(null),[state,setState]=useState('loading'),[retry,setRetry]=useState(0),[tab,setTab]=useState('overview'),[share,setShare]=useState('');const data=usePortal();useTitle(item?.name||item?.title||info[type].label);
 useEffect(()=>{const controller=new AbortController();setState('loading');fetch(`/api/public/${type}/${encodeURIComponent(slug)}`,{signal:controller.signal}).then(async r=>{if(r.status===404){setState('missing');return}if(!r.ok)throw new Error();setItem(await r.json());setState('ready')}).catch(e=>{if(e.name!=='AbortError')setState('error')});return()=>controller.abort()},[type,slug,retry]);
 const whatsapp='https://wa.me/'+String(data.settings.whatsapp).replace(/\D/g,'')+'?text='+encodeURIComponent(`Olá! Gostaria de informações sobre ${item?.name||item?.title||'o Instituto'}.`);
 const courseTabs=[['overview','Apresentação'],['formation','A formação'],['admission','Como ingressar']];
 async function copyLink(){try{await navigator.clipboard.writeText(location.href);setShare('Ligação copiada.')}catch{setShare('Copie o endereço na barra do navegador.')}}
 return <PublicLayout>{state==='loading'?<div className="in-detail-loading" role="status">A carregar informações…<div className="in-skeleton-grid"><div/><div/></div></div>:state==='error'?<EmptyState error retry={()=>setRetry(n=>n+1)}/>:state==='missing'?<div className="in-empty"><span className="ps-eyebrow">CONTEÚDO INDISPONÍVEL</span><h1>Esta página não está disponível.</h1><p>O conteúdo pode ter sido removido ou ainda não estar publicado.</p><Link className="ps-button ps-blue" href={'/'+paths[type]}>Voltar a {info[type].label.toLowerCase()} ↗</Link></div>:<>
  <PageBanner eyebrow={type==='courses'?'Formação na área da saúde':type==='events'?'Agenda do Instituto':item.category||'Notícias do Instituto'} title={item.name||item.title} description={item.description||item.summary||''} image={item.image||info[type].image}/>
  <nav className="in-detail-back"><Link href={'/'+paths[type]}>← {type==='courses'?'Todos os cursos':type==='events'?'Todos os eventos':'Todas as notícias'}</Link><button onClick={copyLink}>Partilhar esta página ↗</button><span role="status">{share}</span></nav>
  <div className="in-detail-layout"><article className="in-article">
   {type==='courses'?<><div className="in-tabs" role="tablist" aria-label="Informações do curso">{courseTabs.map(([key,label])=><button key={key} role="tab" id={'tab-'+key} aria-selected={tab===key} aria-controls="course-panel" onClick={()=>setTab(key)}>{label}</button>)}</div><div id="course-panel" role="tabpanel" aria-labelledby={'tab-'+tab}>
    {tab==='overview'&&<><span className="ps-eyebrow">CONHEÇA A SUA PRÓXIMA FORMAÇÃO</span><h2>Sobre o curso</h2><p className="in-lead">{item.description}</p><p>A formação na área da saúde exige conhecimento, responsabilidade e atenção às pessoas. No Paraíso do Saber, o seu percurso começa pela escolha informada do curso que pretende frequentar.</p>{item.objectives&&<section><h2>Objectivos da formação</h2><p>{item.objectives}</p></section>}{item.careerProfile&&<section><h2>Perfil profissional</h2><p>{item.careerProfile}</p></section>}<div className="in-note"><strong>Uma escolha com informação.</strong><p>Converse com a secretaria para conhecer o enquadramento da formação e esclarecer as suas dúvidas antes da matrícula.</p></div></>}
    {tab==='formation'&&<><span className="ps-eyebrow">ORGANIZE O SEU PERCURSO</span><h2>Informações da formação</h2><dl className="in-facts">{[['Duração',item.duration],['Modalidade',item.modality],['Horários',item.schedule],['Local',item.location]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Consulte a secretaria'}</dd></div>)}</dl>{item.curriculum?<section><h2>Plano curricular</h2><p>{item.curriculum}</p></section>:<div className="in-note"><strong>Quer conhecer o plano curricular?</strong><p>Solicite à secretaria as informações actualizadas sobre as disciplinas, a duração e a organização das turmas.</p><a href={whatsapp} target="_blank" rel="noreferrer">Solicitar informações ↗</a></div>}</>}
    {tab==='admission'&&<><span className="ps-eyebrow">O PRÓXIMO PASSO É SEU</span><h2>Como ingressar</h2><p>{item.requirements||'Os requisitos de acesso e a documentação necessária devem ser confirmados com a secretaria, de acordo com o curso e a turma pretendida.'}</p><AdmissionsSteps compact/><Link className="ps-button ps-yellow" href={'/matriculas?curso='+encodeURIComponent(item.name)}>Tenho interesse neste curso ↗</Link></>}
   </div></>:<><div className="in-article-meta"><span>{type==='events'?dateLabel(item.startsAt):dateLabel(item.publishAt||item.createdAt)}</span>{item.author&&<span>Por {item.author}</span>}</div><h2>{type==='events'?'Sobre este encontro':'Informação para a nossa comunidade'}</h2><p className="in-lead">{item.description||item.summary}</p>{item.content&&<div className="in-article-text">{item.content}</div>}{type==='events'&&<dl className="in-facts">{[['Data',dateLabel(item.startsAt)],['Horário',item.time],['Local',item.location],['Participação',item.speaker]].filter(([,v])=>v).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}{item.video&&<video controls preload="none" className="in-article-video"><source src={asset(item.video)}/></video>}{item.registrationUrl&&<a className="ps-button ps-blue" href={item.registrationUrl} target="_blank" rel="noreferrer">Informações e inscrição ↗</a>}{item.tags&&<div className="in-tags">{item.tags.split(',').map((tag:string)=><span key={tag}>{tag.trim()}</span>)}</div>}</>}
  </article><aside className="in-detail-aside"><div className="in-admission-card"><span className="ps-eyebrow">PARAÍSO DO SABER</span><h2>{type==='courses'?'O seu futuro começa com uma escolha.':'Faça parte da nossa comunidade.'}</h2><p>A nossa equipa está disponível para o acompanhar e esclarecer as suas dúvidas.</p><Link className="ps-button ps-yellow" href={'/matriculas'+(type==='courses'?'?curso='+encodeURIComponent(item.name):'')}>{type==='courses'?'Tenho interesse':'Fale com a equipa'} ↗</Link><a href={whatsapp} target="_blank" rel="noreferrer" className="in-whatsapp-link">Conversar pelo WhatsApp ↗</a><hr/><small>CONTACTE A SECRETARIA</small><a href={'tel:'+data.settings.phone1.replace(/\s/g,'')}>{data.settings.phone1}</a></div><div className="in-aside-note"><span>✚</span><strong>Educação com propósito.</strong><p>Conhecimento, responsabilidade e cuidado com as pessoas.</p></div></aside></div>
  {type==='courses'&&<section className="in-related"><div className="ps-section-heading"><div><span className="ps-eyebrow">OUTROS CAMINHOS NA SAÚDE</span><h2>Explore outras formações</h2></div><Link href="/cursos">Ver todos ↗</Link></div><div className="in-related-grid">{data.courses.filter((c:any)=>c.slug!==slug).slice(0,2).map((c:any)=><Link href={'/cursos/'+c.slug} key={c.slug}><img src={asset(c.image||'/banner1.jpeg')} alt=""/><div><small>FORMAÇÃO EM SAÚDE</small><h3>{c.name}</h3><span>Conhecer o curso ↗</span></div></Link>)}</div></section>}<CallToAction/>
 </>}</PublicLayout>
}
