import { Body,Controller,Get,Post,Put,Delete,Param,Query,Req,Res,UseInterceptors,UploadedFile,BadRequestException,ForbiddenException } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { diskStorage } from 'multer';
import { basename,extname,join } from 'path';
import { unlink } from 'fs/promises';
import { randomUUID } from 'crypto';
import { Request,Response } from 'express';
import { PrismaService } from './prisma.service';
import { JwtService } from '@nestjs/jwt';
import { compare,hash } from 'bcryptjs';
import { Public,Roles,CurrentUser } from './auth';
const safeUser=(u:any)=>({id:u.id,email:u.email,name:u.name,role:u.role});
@Controller('api') export class AppController {constructor(private db:PrismaService,private jwt:JwtService){}
 @Public() @Get('health') health(){return {status:'ok'}}
 @Public() @Post('auth/login') async login(@Body() body:any){const u=await this.db.user.findUnique({where:{email:String(body.email||'').toLowerCase()}});if(!u||!u.active||!await compare(body.password||'',u.passwordHash))throw new BadRequestException('E-mail ou palavra-passe inválidos');return {token:await this.jwt.signAsync({sub:u.id,email:u.email,role:u.role,name:u.name}),user:safeUser(u)}}
 @Get('auth/me') me(@CurrentUser() user:any){return user}
 @Public() @Get('public/home') async home(){const now=new Date();const [courses,events,news,campaigns,sections,settings]=await Promise.all([this.db.course.findMany({where:{status:'ACTIVE'},orderBy:{createdAt:'desc'}}),this.db.event.findMany({where:{publication:'PUBLISHED',startsAt:{gte:now}},orderBy:{startsAt:'asc'},take:4}),this.db.news.findMany({where:{OR:[{status:'PUBLISHED',OR:[{publishAt:null},{publishAt:{lte:now}}]},{status:'SCHEDULED',publishAt:{lte:now}}]},orderBy:{publishAt:'desc'},take:3}),this.db.campaign.findMany({where:{status:{in:['PUBLISHED','SCHEDULED']},AND:[{OR:[{startsAt:null},{startsAt:{lte:now}}]},{OR:[{endsAt:null},{endsAt:{gte:now}}]}]},orderBy:{order:'asc'}}),this.db.homeSection.findMany({orderBy:{order:'asc'}}),this.db.siteSetting.findMany()]);return {courses,events,news,campaigns,sections,settings:Object.fromEntries(settings.map(x=>[x.key,x.value]))}}
 @Public() @Get('public/courses') async publicCourses(@Query('q') q?:string){return this.db.course.findMany({where:{status:'ACTIVE',...(q?{OR:[{name:{contains:q,mode:'insensitive'}},{area:{contains:q,mode:'insensitive'}}]}:{})},orderBy:[{featured:'desc'},{name:'asc'}]})}
 @Public() @Get('public/courses/:slug') publicCourse(@Param('slug') slug:string){return this.db.course.findUnique({where:{slug}})}
 @Public() @Get('public/events/:slug') publicEvent(@Param('slug') slug:string){return this.db.event.findUnique({where:{slug}})}
 @Public() @Get('public/events') publicEvents(){return this.db.event.findMany({where:{publication:'PUBLISHED'},orderBy:{startsAt:'asc'}})}
 @Public() @Get('public/news') publicNews(){return this.db.news.findMany({where:{status:'PUBLISHED',OR:[{publishAt:null},{publishAt:{lte:new Date()}}]},orderBy:{publishAt:'desc'}})}
 @Public() @Get('public/news/:slug') publicNewsItem(@Param('slug') slug:string){return this.db.news.findUnique({where:{slug}})}
 @Public() @Get('public/media') publicMedia(){return this.db.media.findMany({where:{mimeType:{startsWith:'image/'}},orderBy:{createdAt:'desc'}})}
 @Public() @Post('public/leads') async createLead(@Body() b:any,@Req() req:Request){if(!b.name||!b.phone)throw new BadRequestException('Nome e telefone são obrigatórios');return this.db.lead.create({data:{name:b.name,phone:b.phone,whatsapp:b.whatsapp,email:b.email,course:b.course,municipality:b.municipality,notes:b.notes}})}
 @Get('admin/dashboard') @Roles('ADMIN','EDITOR','ATTENDANCE') async dashboard(){const [courses,events,campaigns,news,leads,media]=await Promise.all([this.db.course.count({where:{status:'ACTIVE'}}),this.db.event.count({where:{startsAt:{gte:new Date()}}}),this.db.campaign.count({where:{status:'PUBLISHED'}}),this.db.news.count({where:{status:'PUBLISHED'}}),this.db.lead.count(),this.db.media.count()]);return {courses,events,campaigns,news,leads,media}}
 @Get('admin/:entity') @Roles('ADMIN','EDITOR','ATTENDANCE') async list(@Param('entity') entity:string,@Query() q:any,@CurrentUser() user:any){this.assertEntity(user,entity,false);const model=this.model(entity);if(entity==='leads')return model.findMany({where:{...(q.status?{status:q.status}:{}),...(q.course?{course:{contains:q.course,mode:'insensitive'}}:{})},orderBy:{createdAt:'desc'}});if(entity==='audit')return this.db.auditLog.findMany({include:{user:{select:{name:true,email:true}}},orderBy:{createdAt:'desc'},take:200});if(entity==='users')return model.findMany({select:{id:true,email:true,name:true,role:true,active:true,createdAt:true},orderBy:{createdAt:'desc'}});return model.findMany({orderBy:entity==='sections'?{order:'asc'}:{createdAt:'desc'}})}
 @Post('admin/:entity') @Roles('ADMIN','EDITOR') async create(@Param('entity') entity:string,@Body() data:any,@CurrentUser() user:any,@Req() req:Request){this.assertEntity(user,entity,true);const model=this.model(entity);const clean=this.clean(entity,data);if(entity==='courses'){clean.status=clean.status||'ACTIVE';clean.description=clean.description||''}if(entity==='events'){clean.status=clean.status||'UPCOMING';clean.publication=clean.publication||'DRAFT';clean.description=clean.description||''}if(entity==='campaigns')clean.status=clean.status||'DRAFT';if(entity==='news'){clean.status=clean.status||'DRAFT';clean.category=clean.category||'Institucional';clean.summary=clean.summary||'';clean.content=clean.content||''}if(entity==='users'){if(!data.password)throw new BadRequestException('Defina uma palavra-passe inicial');clean.passwordHash=await hash(data.password,12);delete clean.password;clean.email=String(clean.email||'').toLowerCase();clean.role=clean.role||'EDITOR'}const row=await model.create({data:clean});await this.audit(user,req,'CREATE',entity,row.id);if(entity==='users'){delete row.passwordHash}return row}
 @Put('admin/:entity/:id') @Roles('ADMIN','EDITOR','ATTENDANCE') async update(@Param('entity') entity:string,@Param('id') id:string,@Body() data:any,@CurrentUser() user:any,@Req() req:Request){this.assertEntity(user,entity,true);const clean=this.clean(entity,data);if(entity==='users'&&data.password)clean.passwordHash=await hash(data.password,12);const row=await this.model(entity).update({where:{id},data:clean});await this.audit(user,req,'UPDATE',entity,id);if(entity==='users')delete row.passwordHash;return row}
 @Delete('admin/:entity/:id') @Roles('ADMIN','EDITOR') async remove(@Param('entity') entity:string,@Param('id') id:string,@CurrentUser() user:any,@Req() req:Request){this.assertEntity(user,entity,true);if(entity==='media'){const media=await this.db.media.findUnique({where:{id}});if(media)await unlink(join(process.cwd(),'uploads',basename(media.filename))).catch(()=>undefined)}await this.model(entity).delete({where:{id}});await this.audit(user,req,'DELETE',entity,id);return {success:true}}
 @Get('admin/settings') @Roles('ADMIN','EDITOR') async settings(){return Object.fromEntries((await this.db.siteSetting.findMany()).map(x=>[x.key,x.value]))}
 @Put('admin/settings') @Roles('ADMIN') async saveSettings(@Body() b:any,@CurrentUser() user:any,@Req() req:Request){for(const [key,value] of Object.entries(b))await this.db.siteSetting.upsert({where:{key},update:{value:String(value)},create:{key,value:String(value)}});await this.audit(user,req,'UPDATE','settings','general');return this.settings()}
 @Put('admin/home-sections/:id') @Roles('ADMIN','EDITOR') async updateSection(@Param('id') id:string,@Body() body:any){return this.db.homeSection.update({where:{id},data:body})}
 @Post('admin/upload') @Roles('ADMIN','EDITOR') @UseInterceptors(FileInterceptor('file',{limits:{fileSize:100*1024*1024},storage:diskStorage({destination:'uploads',filename:(_req,file,cb)=>cb(null,`${randomUUID()}${extname(file.originalname).toLowerCase()}`)}),fileFilter:(_req,file,cb)=>file.mimetype.startsWith('image/')||file.mimetype.startsWith('video/')||file.mimetype==='application/pdf'?cb(null,true):cb(new Error('Tipo de ficheiro não permitido'),false)})) async upload(@UploadedFile() file:any){if(!file)throw new BadRequestException('Ficheiro inválido');return this.db.media.create({data:{filename:file.filename,originalName:file.originalname,mimeType:file.mimetype,url:`/media/${file.filename}`,size:file.size}})}
 @Get('admin/leads/export.csv') @Roles('ADMIN','EDITOR','ATTENDANCE') async exportLeads(@Query() q:any,@Res() res:Response){const rows=await this.db.lead.findMany({where:{...(q.status?{status:q.status}:{}),...(q.course?{course:{contains:q.course,mode:'insensitive'}}:{}),...(q.from||q.to?{createdAt:{...(q.from?{gte:new Date(q.from)}:{}),...(q.to?{lte:new Date(q.to)}:{})}}:{})},orderBy:{createdAt:'desc'}});const csv=[['Nome','Telefone','WhatsApp','E-mail','Curso','Município','Estado','Data'],...rows.map(x=>[x.name,x.phone,x.whatsapp||'',x.email||'',x.course||'',x.municipality||'',x.status,x.createdAt.toISOString()])].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\r\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="interessados.csv"');return res.send(`\uFEFF${csv}`)}
 private model(e:string):any{const map:any={courses:this.db.course,events:this.db.event,campaigns:this.db.campaign,news:this.db.news,media:this.db.media,leads:this.db.lead,sections:this.db.homeSection,users:this.db.user};if(!map[e])throw new BadRequestException('Área desconhecida');return map[e]}
 private assertEntity(user:any,entity:string,write:boolean){if(user.role==='ADMIN')return;if(user.role==='EDITOR'&&['courses','events','campaigns','news','media','sections'].includes(entity))return;if(user.role==='ATTENDANCE'&&entity==='leads'&&(write||!write))return;throw new ForbiddenException('A sua conta não tem permissão para esta área')}
 private clean(e:string,d:any){const data={...d};delete data.id;delete data.createdAt;delete data.updatedAt;delete data.password;delete data.passwordHash;if(['courses','news','events'].includes(e)&&!data.slug){const source=data.name||data.title;if(source)data.slug=source.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}for(const key of ['featured','active','enabled'])if(typeof data[key]==='string')data[key]=data[key]==='true';if(typeof data.order==='string')data.order=Number(data.order);for(const key of ['startsAt','endsAt','publishAt'])if(data[key]==='')delete data[key];return data}
 private audit(user:any,req:Request,action:string,entity:string,entityId:string){return this.db.auditLog.create({data:{userId:user.sub,action,entity,entityId,ip:req.ip}})}
}
