const {chromium}=require('@playwright/test');
const fs=require('fs');
(async()=>{
  fs.mkdirSync('artifacts',{recursive:true});
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:8000/',{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Pausar destaques'}).click();
  await page.screenshot({path:'artifacts/portal-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Mostrar destaque 2',exact:true}).click();
  await page.getByRole('heading',{name:'Aprender hoje. Cuidar amanhã.'}).waitFor();
  await page.getByRole('textbox',{name:'Pesquisar cursos',exact:true}).fill('Farmácia');
  if(await page.locator('.ps-course-card').count()!==1)throw new Error('Pesquisa não filtrou o curso');
  await page.getByRole('button',{name:'Limpar pesquisa',exact:true}).click();
  if(await page.locator('.ps-course-card').count()!==3)throw new Error('Pesquisa não foi limpa');
  await page.route('**/api/public/leads',route=>route.fulfill({status:201,contentType:'application/json',body:'{"status":"NEW"}'}));
  await page.getByLabel('Nome completo',{exact:true}).fill('Verificação visual');
  await page.getByLabel('Telefone / WhatsApp',{exact:true}).fill('+244900000000');
  await page.getByRole('button',{name:'Quero receber informações'}).click();
  await page.getByRole('status').filter({hasText:'Recebido!'}).waitFor();
  await page.route('**/api/public/leads',route=>route.fulfill({status:422,contentType:'application/json',body:'{"message":"Validation error"}'}));
  await page.getByLabel('Nome completo',{exact:true}).fill('Verificação visual');
  await page.getByLabel('Telefone / WhatsApp',{exact:true}).fill('+244900000000');
  await page.getByRole('button',{name:'Quero receber informações'}).click();
  await page.getByRole('status').filter({hasText:'Não foi possível enviar'}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://127.0.0.1:8000/',{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Pausar destaques'}).click();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  if(overflow)throw new Error('Página ultrapassa a largura do telemóvel');
  await page.screenshot({path:'artifacts/portal-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
  await page.locator('.ps-sidebar.is-open').waitFor();
  await page.locator('.ps-sidebar-links').getByRole('link',{name:'O Instituto'}).click();
  if(await page.locator('.ps-sidebar.is-open').count())throw new Error('Menu não fechou após navegação');
  await page.goto('http://127.0.0.1:8000/cursos/farmacia',{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'Farmácia',exact:true}).waitFor();
  await page.goto('http://127.0.0.1:8000/admin',{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Entrar no painel'}).waitFor();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('OK: desktop, mobile, carrossel, pesquisa, formulário (respostas simuladas), navegação, curso e login; sem erros JavaScript.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
